import json
import sys
import os

def fix_spdx_sbom(spdx_file_path, cdx_file_path=None):
    """
    Fixes common issues in SPDX SBOMs generated by conversion tools to ensure compatibility with Snyk.
    - Ensures all packages have a non-empty 'name'.
    - Carries over information from CycloneDX if available (placeholder for future expansion).
    """
    print(f"[-] Running SPDX SBOM Fixer on: {spdx_file_path}")
    
    if not os.path.exists(spdx_file_path):
        print(f"Error: File not found: {spdx_file_path}")
        sys.exit(1)

    with open(spdx_file_path, 'r') as f:
        try:
            spdx_data = json.load(f)
        except json.JSONDecodeError as e:
            print(f"Error decoding JSON: {e}")
            sys.exit(1)
        
    packages = spdx_data.get('packages', [])
    fixed_count = 0
    
    # Build a lookup from CycloneDX if provided
    cdx_lookup = {}
    if cdx_file_path and os.path.exists(cdx_file_path):
        print(f"[-] Loading CycloneDX source: {cdx_file_path}")
        try:
            with open(cdx_file_path, 'r') as f:
                cdx_data = json.load(f)
                for comp in cdx_data.get('components', []):
                    # Key by bom-ref if available, otherwise we can't easily map
                    if 'bom-ref' in comp:
                        cdx_lookup[comp['bom-ref']] = comp
        except Exception as e:
            print(f"Warning: Failed to load CycloneDX file: {e}")

    for pkg in packages:
        name = pkg.get('name', '').strip()
        spdx_id = pkg.get('SPDXID', 'UNKNOWN')
        
        # Issue 1: Missing Name
        if not name:
            print(f"    ! Found package with empty name. SPDXID: {spdx_id}")
            
            # Attempt to recover from CycloneDX if we can map the IDs
            # Syft conversion usually maps bom-ref to something inside SPDXID or relatedSpdxElement
            # But the mapping isn't always 1:1 string equality.
            # The broken package had SPDXID: "SPDXRef-Package-UnknownPackage-13cfb6ba..."
            # The CycloneDX bom-ref was: "13cfb6ba..."
            
            new_name = "Unknown_Component" # Default fallback
            
            # Extract potential ID from SPDXID
            # standard Syft format: SPDXRef-Package-<name>-<id>
            parts = spdx_id.split('-')
            potential_ref = parts[-1] 
            
            if potential_ref in cdx_lookup:
                cdx_comp = cdx_lookup[potential_ref]
                if cdx_comp.get('name'):
                    new_name = cdx_comp['name']
                    print(f"      > Recovered name from CycloneDX: {new_name}")
            
            # If still unknown, use SPDXID segment
            if new_name == "Unknown_Component":
                 new_name = f"Component_{potential_ref}"
            
            pkg['name'] = new_name
            fixed_count += 1

    if fixed_count > 0:
        print(f"[-] Fixed {fixed_count} packages.")
        with open(spdx_file_path, 'w') as f:
            json.dump(spdx_data, f, indent=2)
        print("[-] SPDX SBOM saved.")
    else:
        print("[-] No packages required fixing.")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python fix_spdx_sbom.py <spdx_file> [cdx_file]")
        sys.exit(1)
        
    spdx_path = sys.argv[1]
    cdx_path = sys.argv[2] if len(sys.argv) > 2 else None
    
    fix_spdx_sbom(spdx_path, cdx_path)
